### ISSUE TITLE
Question: is it possible to subscribe a port to system announcer ?

### ISSUE THREAD

**Issue by Houston4444** [alsa-project/alsa-python#7]
Hi. I try to add ALSA support to [Patchance](https://github.com/Houston4444/Patchance).

I 'd like to create a port capable to receive events as SEQ_EVENT_PORT_START or SEQ_EVENT_PORT_EXIT in order to get a complete graph.

I see in patchage source code (C++) that it uses 'snd_seq_connect_from' function to enable this events.

Is it possible in python with this lib ?

Thanks.

**Comment by perexg** [comment]
Perhaps, you already resolved this. You need to subscribe SEQ_PORT_SYSTEM_ANNOUNCE port like in https://github.com/alsa-project/alsa-python/blob/master/test/seqtest2.py .
